extends:
  - "plugin:prettier/recommended"

env:
  browser: true
  node: true

parserOptions:
  ecmaVersion: 5

rules:
  strict: [error, "global"]

overrides:
  - files: "*.test.*"
    plugins:
      - mocha
    env:
      mocha: true
    rules:
      mocha/handle-done-callback: error
      mocha/no-exclusive-tests: error
      mocha/no-global-tests: error
      mocha/no-hooks-for-single-case: off
      mocha/no-identical-title: error
      mocha/no-mocha-arrows: error
      mocha/no-nested-tests: error
      mocha/no-return-and-callback: error
      mocha/no-sibling-hooks: error
      mocha/no-skipped-tests: error
      mocha/no-top-level-hooks: error
